language: python
python:
  - "3.7"

stages:
  - test
  - name: documentation
    if: branch = master AND type = push

before_install:
  - cd ..
  # Install miniconda
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  # Update conda
  # - conda update --yes conda
  - conda update -y -n base conda setuptools
  - conda info -a
  # Set git info
  - git config --global user.name "Travis Deploy"
  - git config --global user.email "alongd@mit.edu"

cache: pip

jobs:
  include:
    - stage: test
      install:
        - cd ARC
        - export PYTHONPATH=$PYTHONPATH:$(pwd)
        - conda env create -q -f environment.yml
        - source activate arc_env
        - cd ..
        - git clone https://github.com/ReactionMechanismGenerator/RMG-Py
        - cd RMG-Py
        - export PYTHONPATH=$PYTHONPATH:$(pwd)
        - make
        - cd ..
        - git clone https://github.com/ReactionMechanismGenerator/RMG-database
        - cd RMG-database
        - cd ..
        - git clone https://github.com/ReactionMechanismGenerator/AutoTST
        - cd AutoTST
        - git checkout -b py3 origin/py3
        - export PYTHONPATH=$PYTHONPATH:$(pwd)
        - cd ..
        - conda install -y -c conda-forge codecov
        - conda list
        - cd ARC
      script:
        - make test
        - codecov --token=f259713a-7f1d-4e9c-b140-bb3bb371d3ef
    - stage: documentation
      install:
        - cd ARC
        - export PYTHONPATH=$PYTHONPATH:$(pwd)
        - conda env create -q -f environment.yml
        - source activate arc_env
        - cd ..
        - git clone https://github.com/ReactionMechanismGenerator/RMG-Py
        - cd RMG-Py
        - export PYTHONPATH=$PYTHONPATH:$(pwd)
        - make
        - cd ..
        - git clone https://github.com/ReactionMechanismGenerator/RMG-database
        - git clone https://github.com/ReactionMechanismGenerator/AutoTST
        - cd AutoTST
        - git checkout -b py3 origin/py3
        - export PYTHONPATH=$PYTHONPATH:$(pwd)
        - cd ../ARC/docs
        # Install sphinx for building the documentation
        - conda install -y sphinx
        - conda install -y -c anaconda sphinx_rtd_theme
        - conda list
        - export COMMITMESSAGE="Automatic documentation rebuild"
      script:
        - make travis_setup clean html publish
