name: arc_env
channels:
  - defaults
  - rmg
  - omnia
  - conda-forge
  - anaconda
dependencies:
  - libgcc # [unix]
  - python
  - numpy >=1.11.3
  - cantera >=2.3.0a3
  - coolprop
  - cython >=0.25.2
  - matplotlib >=2.2.2
  - rdkit >=2015.09.2
  - pydas >=1.0.1
  - pydqed >=1.0.0
  - lpsolve55
  - quantities
  - scipy
  - xlwt
  - markupsafe
  - jinja2
  - pyparsing
  - pydot ==1.2.2
  - pyrdl
  - nose
  - coverage
  - gprof2dot
  - cairo
  - cairocffi
  - openbabel
  - psutil
  - symmetry
  - mopac
  - graphviz
  - scoop
  - libgfortran >=1.0 # You may need to comment this out for mac osx
  - ffmpeg
  - jupyter
  - networkx
  - mock
  - muq
  - pymongo
  - mpmath
  - dde
  - pydot-ng
  - pyyaml
  - paramiko >=2.4.2
  - cclib >=1.6
  - py3Dmol >=0.8.0
  - ase >=3.15.0
  - tensorflow
  - scikit-learn
