name: arc_env
channels:
  - defaults
  - rmg
  - rdkit
  - cantera
  - anaconda
  - omnia
  - pytorch
  - conda-forge
  - psi4
dependencies:
  - cairo
  - cairocffi
  - cantera >=2.3.0
  - cclib >=1.6
  - chemprop
  - coolprop
  - coverage
  - cython >=0.25.2
  - ffmpeg
  - gprof2dot
  - graphviz
  - h5py
  - jinja2
  - jupyter
  - lpsolve55
  - mako
  - markupsafe
  - matplotlib >=2.2.2
  - mock
  - mopac
  - mpmath
  - networkx
  - nose
  - numdifftools
  - numpy >=1.15.4
  - openbabel
  - pandas >=1.0.1
  - psutil
  - psi4
  - pydas >=1.0.1
  - pydot
  - pydqed >=1.0.0
  - pymongo
  - pyparsing
  - pyrdl
  - pytables
  - python >=3.7
  - pyyaml
  - quantities
  - rdkit >=2019.09.2.0
  - scikit-learn
  - scipy
  - sphinx_rtd_theme
  - symmetry
  - xlwt
  - paramiko >=2.6.0
  - py3dmol >= 0.8.0
  - ase >=3.15.0
  - ipython
  - sphinx
  - qcelemental
