name: arc_env

channels:
  - conda-forge

dependencies:
  # ─── core ─────────────────────────────────────
  - conda-forge::python >=3.12.*
  - conda-forge::numpy  >=2.1.*
  - conda-forge::pip

  # ─── core networking (for Jupyter notebooks) ──
  - conda-forge::urllib3
  - conda-forge::requests
  - conda-forge::six

  # ─── conda-forge packages ─────────────────────
  - conda-forge::ase >=3.22.1
  - conda-forge::cairo
  - conda-forge::cairocffi
  - conda-forge::cmake
  - conda-forge::coverage
  - conda-forge::cython >=3.0
  - conda-forge::ffmpeg
  - conda-forge::gprof2dot
  - conda-forge::graphviz
  - conda-forge::h5py
  - conda-forge::ipython
  - conda-forge::jupyter
  - conda-forge::lpsolve55
  - conda-forge::mako
  - conda-forge::matplotlib
  - conda-forge::networkx
  - conda-forge::openbabel >=3
  - conda-forge::pandas
  - conda-forge::paramiko >=2.6.0
  - conda-forge::py3dmol >=0.8.0
  - conda-forge::pydot
  - conda-forge::pytables
  - conda-forge::pytest
  - conda-forge::pytest-cov
  - conda-forge::pytest-xdist
  - conda-forge::pyyaml
  - conda-forge::rdkit >=2025.03
  - conda-forge::scipy
  - conda-forge::sphinx
  - conda-forge::sphinx_rtd_theme
  - conda-forge::sphinxcontrib-jsmath
