name: tani_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python =3.10.8
  - numpy =1.24
  - pandas
  - ase
  - torchani =2.2
  - pytorch =1.13.1
  - torchvision =0.14.1
  - torchaudio =0.13.1
  - cpuonly
  - scikit-learn
  - matplotlib
  - ipython
  - pyyaml
  - typing-extensions
